### ISSUE TITLE
Use Side Effects to Update the Total Price Immediately After Adding Another Booking

### ISSUE THREAD

**Issue by sammok83** [SAP-samples/fiori-elements-v4-cap-advanced#92] opened 2024-05-01 12:40 UTC
Hi there,

When checking out this branch (Use Side Effects to Update the Total Price Immediately After Adding Another Booking
) and running it in VScode - this seems to not be working (Total Price is not updated immediately). Also Total price is not even updating correctly after a save.

**Comment by TanyaMedvedeva** [comment] 2024-06-03 08:32
hi,
thanks for reporting the issue. You are right that the problem is not with the side effects ( what this exercise is for) but that Saving of the draft does not update the total price. We have found the solution for that and will update the Node js methods of the app for handling draft correspondingly.

**Comment by TanyaMedvedeva** [comment] 2024-09-17 10:16
hi,
now side effects should work fine again so closing the issue.

**Closed by TanyaMedvedeva** 2024-09-17 10:16 UTC
